### ISSUE TITLE
Compilation failure when including email address in footnote

### ISSUE THREAD

**Issue by JostMigenda** [openjournals/whedon#107]
We tried to include the email address of the corresponding author in the footnote, [like this](https://github.com/SNEWS2/snewpy/commit/b696a5a153a531e48d4e2c4d925537686f485574):
```
authors:
  - name: 'James P. Kneller^[Corresponding author: jpknelle@ncsu.edu]'
    orcid: 0000-0002-3502-3830
    affiliation: 4
```
and got the following error message when trying to [generate a preview](https://whedon.theoj.org) of the paper:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/16189747/128947093-2067fe67-d477-4fb1-b0de-6bee1cace9e3.png">

After removing the email address, the paper compiles successfully. Is there a workaround that would allow us to include an email address for the corresponding author?
