### ISSUE TITLE
Whedon should fail when no affiliation set

### ISSUE THREAD

**Issue by arfon** [openjournals/whedon#55]
In https://github.com/openjournals/joss-reviews/issues/1511 we had a paper where there was no affiliation set for an author so possibly the LaTeX template defaulted to the first one. This resulted in Whedon not being able to deposit the metadata with the JOSS API.

For reference, the YAML header looked like this:

```
---
title: 'swisslandstats-geopy: Python tools for the land statistics datasets from the Swiss Federal Statistical Office'
tags:
  - Python
  - land use
  - land cover
  - GIS
  - raster
authors:
 - name: Martí Bosch
   orcid: 0000-0001-8735-9144
affiliations:
 - name: Urban and Regional Planning Community, École Polytechnique Fédérale de Lausanne, Switzerland
date: 17 May 2019
bibliography: paper.bib
---
```
